# Generated by Django 3.0.5 on 2024-02-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='My Freakin awesome blog', max_length=255),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
